### ISSUE TITLE
Questions about alpine branch, etcd and percona-xtrabackup

### ISSUE THREAD

**Issue by ahoeg** [Flowman/docker-pxc#4]
Hello @Flowman,

I used your "old" template from rancher community catalog, but it's old and not maintained. 

So I searched for newer mysql-cluster and found your alpine branch and custom catalog. It's updated some month ago. Could you describe the difference to the old image?

1. Is the alpine branch stable / maintained?
1. Why etcd is used (would be nice to know ;) )
1. Is percona-xtrabackup integrated for automatic database backups? How could it used?

**Comment by ahoeg** [comment]
2. etcd
The old stack was without etcd and so it wasn't an additional cause of failure? I haven't worked with etcd before so I don't know how "stable" it will be. Or would pcx restore / re-init the etcd data if it was crashed / deleted and redeployed?

**Comment by Flowman** [comment]
Hi @ahoeg 

Sorry for a late answer. I was preparing to use kubernetes as rancher was moving to use kubernetes. So that is why I decided to use etcd.

If you are using Rancher 2.0 check out the percona-xtradb-cluster helm chart. I have just updates the alpine images with the latest release of PXC to use with that chart.

The alpine branch is experimental. I'm using it in my own production environments, So it gets updated when I need a new version for my cluster :)

Cheers
